cloudfile:
  gorm-gen:
    model: "./model"
    dal: "./internal/cloudfile/dal"
  mysql:
    dsn: "user:password@tcp(example.com:3306)/db_name?charset=utf8&parseTime=True&loc=Local&timeout=100s"
  oss:
    endpoint: "https://oss-cn-hangzhou.aliyuncs.com"
    accessKeyID: "LTAI5tJq4adsffd9WQqHP"
    accessKeySecret: "sdsffffffffffdads5TGnFkIWc25"
    bucketName: "bucket-cloud-file"